# Problemanalyse

## Statistik og historien bag

Ordet _statistik_ stammer tilbage fra det latinske _statisticum collegium_ ("statsrådgiver") og det italienske _statista_ ("statsmand" eller "politiker"). [@Orddef] At statistik netop stammer derfra, giver god mening, under anskueelse af betydningen af disse to ord og den tidlige anvendelse af statistik. I takt med udviklingen af suverænitetsstaterne, steg behovet for at registrere befolkningen og dennes tilhørselsforhold. Derfor anvendte statsrådgivere og statsmænd statistik til at beskrive staten, særligt demografien. Senerere blev dette udvidet til at indsamle flere informationer, og ligeledes at analysere og fortolke disse ved hjælp af statistik.



Selve ordet statistik fandt sin vej til Danmark i 1749, via den tyske statistiker Gottfried Achenwall, som var den første, der anvendte ordet _statistik_ til at beskrive sine studier indenfor netop dette emne. [@O]

Udgangspunktet for statistik kommer fra sandsynlighedsregning og læren derfra. Ligesom i sandsynlighedsregning arbejdes der i statistikken med udfald og tilfældigheder, men overordnet beskæftiger statistikken sig med analyse af indsamlet data.

Statistik blev i begyndelsen anvendt som en videnskablig metode til behandling af numerisk data. Særligt blev det anvendt som en metode til grafisk fremstilling af data, men med tiden udvikledes anvendelsesmulighederne sig, og således blev det muligt at beregne statistiske mål, eksempelvis middelværdi. Udviklingen og anvendelsen af statistik er op gennem årene blevet bredere og benyttes i langt højere grad.

Særligt udviklingen af computeren har været med til at gøre anvendelsen af komplicerede statistiske beregninger hurtigere, mere præcise og mere tilgængelige. Anvendelsesområderne for statistik har ligeledes udviklet sig, fra i begyndelsen at være noget staten anvendte til styring af økonomi og befolkningsindblik, til stort set at være repræsenteret i alle større hverv i dag. Den moderne definition af statistik kan beskrives som evnen til at drage konklusioner om generelle tilfælde, _populationer_, på baggrund af enkelte tilfælde, _stikprøver_. [@ASTAbog, s. 1]

Statistisk videnskab giver tre overordnede begreber til anvendelsen. _Design_, som omhandler planlægningen og tilvejebringelsen af data til den undersøgelse der ønskes foretaget. _Beskrivelse_, når data er indsamlet skal der laves en sammenfatning over data og en indledende analyse, således der på et oplyst grundlag kan træffes beslutning om, hvorledes data skal behandles yderligere. _Inferens_, på baggrund af dataanalyse er det muligt at drage konklusioner om den population, der ønskes undersøgt. Forudsigelser, som laves på baggrund af data, kaldes for statistisk inferens. [@ASTAbog, s. 15-16]

## Statistisk inferens

Processen med at bruge dataanalyse til at drage konklusioner om en underliggende population ud fra en stikprøve af populationen, kaldes statistisk inferens. Dette er nyttigt, da det er hurtigere og billigere at indsamle og analysere data fra en delmængde af en population, end hvis der skulle indsamles de potentielt flere milioner observationer i populationen. 

I statistisk inferens differentieres der mellem to metoder, _estimering_ og _hypotesetest_. Når der estimeres på baggrund af en population, bruges stikprøven til at beskrive en ukendt del af populationen. Det kan f.eks være gennemsnitsindkomst af danskere, hvorved der findes et estimat $\hat{\mu}$ som bruges til at beskrive $\mu$. Dette betegnes som et punktestimat, og vil oftest suppleres med at intervalestimat. Årsagen til dette er, at punktestimater i sin essens er tilfældig (det ændrer sig fra stikprøve til stikprøve). Derfor tilstræbes det at anvende et intervalestimat, hvor det kan siges at $\mu$ med 95% sikkerhed ligger, fremfor et punktestimat. Dette kaldes for et konfidensinterval.  
Den anden form for statistisk infernes er hypotesetest. I hypotesetest opstilles først en nulhypotese, $ H_0 $, og en modhypotese, $ H_1 $. Målet er at indsamle nok evidens imod $ H_0 $, så den kan forkastes, og man er dermed blevet klogere på populationen. 
En nulhypotese kunne være, at danskere tjener det samme i gennemsnit som folk fra Sverige. Der vil ved hjælp af forskellige statistike metoder, ses om der er en signifikant forskel i gennemsnittet.
Hvis dette er tilfældet, vil nulhypotesen forkastes og den alternative hypotese vil antages at være sand.

## Intro til simulering?


## Problemformulering

_Hvorvidt kan simulationsstudier bidrage til at højne kvaliteten af dataanalyser?_

1. Hvilke faldgruber skal man være opmærksom på?

2. Hvordan simulerer man data?

a. Hvordan sikrer man en høj kvalitet af simuleret data?

3. Hvad kan man inferere ud fra simuleret data?

4. Hvilke alternativer finder der til statistisk inferens? (Bootstrapping)
