# Problemanalyse

Ordet _statistik_ stammer tilbage fra det latinske _statisticum collegium_ ("statsrådgiver") og det italienske _statista_ ("statsmand" eller "politiker"), [@Orddef]. At statistik netop stammer derfra, giver god mening, under anskueelse af betydningen af disse to ord og den tidlige anvendelse af statistik. I takt med udviklingen af suverænitetsstaterne, steg behovet for at registrere befolkningen og dennes tilhørselsforhold. Derfor anvendte statsrådgivere og statsmænd statistik til at beskrive staten, særligt demografien. Senerere blev dette udvidet til at indsamle flere informationer, og ligeledes at analysere og fortolke disse ved hjælp af statistik.

<!-- Selve ordet statistik fandt sin vej til Danmark i 1749, via den tyske statistiker Gottfried Achenwall, som var den første, der anvendte ordet _statistik_ til at beskrive sine studier indenfor netop dette emne. [@Orddef] -->

Udgangspunktet for statistik kommer fra sandsynlighedsregning og læren derfra. Ligesom i sandsynlighedsregning arbejdes der i statistikken med udfald og tilfældigheder, men overordnet beskæftiger statistikken sig med analyse af indsamlet data.

<!-- Statistik blev i begyndelsen anvendt som en videnskablig metode til behandling af numerisk data. Særligt blev det anvendt som en metode til grafisk fremstilling af data, men med tiden udvikledes anvendelsesmulighederne sig, og således blev det muligt at beregne statistiske mål, eksempelvis middelværdi. Udviklingen og anvendelsen af statistik er op gennem årene blevet bredere og benyttes i langt højere grad. -->

To statiskerere som ligger fundementet til den statiske arbejdsform der bruges i dag er Karl Pearson og Ronald Fisher. 
Karl Pearson var intereseret i at udvikle matematiske metoder til at studere biologisk arv og evolution. Gennem den interesse udsprang en række bidrag til statistiske anelyse metode. Pearson bidrog korrelationskoefficient $(R^2)$ som bruges til at vise, hvor godt en regressionsmodel passer noget givent data. Udover det, lavede han også chi-i-anden-testen, som er en metode der bruges til at teste at ens observerede værdier stemmer overens med de forventede værdier, [@KarlPearsonbrit], [@Chiianden].

Ronald Fisher designede et planteavl eksperiment der ultimativt gav mere information, som krævede mindre tid, penge og anstrengelser. Han erfarede at hans data ikke var forventningsret, hvilket resulteret i upræcise og misledende resultater. Udfra dette introducerede Fisher randomisering. Princippet siger, at et eksperiment skal gentages på et antal kontrolgrupper, og de elementer brugt i eksperimentet skal tilfældig udvælges fra hele populationen. Dette gjorde data forventningsret, som mindsker effekten for variationen i et eksperiment. Udover det har Fisher bidraget med "Analysis of variance", også kaldet ANOVA. Denne model er brugt til at analyserer forskellen mellem en sameling af middelværdier i en stikprøve.
[@RonaldFisher]

Yderligere har udviklingen af computeren været med til at gøre anvendelsen af komplicerede statistiske beregninger hurtigere, mere præcise og mere tilgængelige. Anvendelsesområderne for statistik har ligeledes udviklet sig, fra i begyndelsen at være noget staten anvendte til styring af økonomi og befolkningsindblik, til stort set at være repræsenteret i alle større hverv i dag. Den moderne definition af statistik kan beskrives som evnen til at drage konklusioner om generelle tilfælde, _populationer_, på baggrund af enkelte tilfælde, _stikprøver_, [@ASTAbog, s. 1].

Statistisk videnskab giver tre overordnede begreber til anvendelsen. _Design_, som omhandler planlægningen og tilvejebringelsen af data til den undersøgelse der ønskes foretaget. _Beskrivelse_, når data er indsamlet skal der laves en sammenfatning over data og en indledende analyse, således der på et oplyst grundlag kan træffes beslutning om, hvorledes data skal behandles yderligere. _Inferens_, på baggrund af dataanalyse er det muligt at drage konklusioner om den population, der ønskes undersøgt. Forudsigelser, som laves på baggrund af data, kaldes for statistisk inferens, [@ASTAbog, s. 15-16].

## Statistisk inferens

Det følgende afsnit er baseret på [@ASTAkursus1], [@ASTAkursus2] og [@ASTAkursus3].

Processen med at bruge dataanalyse til at drage konklusioner om en underliggende population ud fra en stikprøve af populationen, kaldes statistisk inferens. Dette er nyttigt, da det er hurtigere og billigere at indsamle og analysere data fra en delmængde af en population, end hvis der skulle indsamles de potentielt flere milioner observationer i populationen. 

I statistisk inferens differentieres der mellem to metoder, _estimering_ og _hypotesetest_. Når der estimeres på baggrund af en population, bruges stikprøven til at beskrive en ukendt del af populationen. Det kan f.eks være gennemsnitsindkomst af danskere, hvorved der findes et estimat $\hat{\mu}$ som bruges til at beskrive $\mu$. Dette betegnes som et punktestimat, og vil oftest suppleres med at intervalestimat. Årsagen til dette er, at punktestimater i sin essens er tilfældig (det ændrer sig fra stikprøve til stikprøve). Derfor tilstræbes det at anvende et intervalestimat, hvor det kan siges at $\mu$ med $95\%$ sikkerhed ligger, fremfor et punktestimat. Dette kaldes for et konfidensinterval.  

Den anden form for statistisk infernes er hypotesetest. I hypotesetest opstilles først en nulhypotese, $H_0$, og en alternativ hypotese, $H_1$. __FIXME__ (Den her sætning synes jeg skal omskrives) Målet er at indsamle nok evidens imod $H_0$, så den kan forkastes, og man er dermed blevet klogere på populationen. 
En nulhypotese kunne være, at danskere tjener det samme i gennemsnit som folk fra Sverige. Der vil ved hjælp af forskellige statistike metoder, ses om der er en signifikant forskel i gennemsnittet.
Hvis dette er tilfældet, vil nulhypotesen forkastes og den alternative hypotese vil antages at være sand.

## Problemformulering

_Kan simuleringsstudier bidrage til at højne kvaliteten af dataanalyser, og i så fald, hvordan?_

1. Hvilke faldgruber skal man være opmærksom på ved hypotesetest?

2. Hvordan simulerer en computer data?

3. Hvordan kan teoretiske resultater eftervises ved hjælp af simulering?

FIXME: arbejdsspørgsmål i samme rækkefølge som i rapporten. Ret løbende.








