# Perspektivering

Simuleringsstudier medfører mange retninger projektet kunne have inddraget, såvel som mere dybdegående analysemetoder. Dette er dog undladt, blandt andet, på baggrund af manglende computerkraft samt begrænset tid. 

Det kunne have været interesseant at undersøge om permutationer kunne bruges til at lave konfidensintervaller og sammenligne dækningsgraden af disse med bootstrap. 

Da det blev undersøgt, hvordan bootstrap kunne benyttes til at beregne standardfejl blev der kun givet et eksempel på standardfejlen for middelværdi. Her kunne det have været relevant at lave udregningen for en estimator, hvis standardfejl ikke umiddelbart let kunne beregnes.

I rapporten benyttes udelukkende ikke-parametrisk bootstrap. Der findes dog også parametrisk bootstrap, som skiller sig ud fra den ikke-parametriske bootstrap, ved at den antager at stikprøven stammer fra en specifik fordeling, $F$, der afhænger af en specifik parameter, $\theta$. Stikprøven har da punktestimatet $\hat{\theta}$, og det er derved muligt at simulere bootstrap-stikprøver fra fordelingen, $F(\hat{\theta})$. Punktestimatet, $\hat{\theta}$, estimeres oftest ved hjælp af _maximum likelihood estimation_ (MLE). Det kunne have været interessant at undersøge, hvordan begge typer bootstrap ville håndtere samme stikprøver og sammenligne resulaterne. 
For bedst muligt at kunne anvende parametrisk bootstrap, anvendes MLE til at estimere parameteren, $\theta$. Derfor er en forståelse af MLE en forudsætning, der også skulle have været inddraget i projektet, for at kunne have anvendt parametrisk bootstrap.

