
```{r}
stikfunc <- function(pop, n){
  # Input
  ##  pop:    Population, der skal tages en stikprøve fra.
  ##  n:      Størrelse af stikprøven.
  #
  # Output:   En stikprøve fra populationen, pop, af størrelsen n.
  return(sample(pop, n))
}
```

```{r}
library(boot)
konf <- function(pop, n, B, alpha, KI_type){
  # Input
  ##  pop:     Population, der skal tages en stikprøve fra.
  ##  n:       Størrelse af stikprøven.
  ##  B:       Antal bootstrap-stikprøver.
  ##  alpha:   Konfidensniveau.
  ##  KI_type: Type af konfidensinterval. 
  #
  # Output:    Et 1-alpha%-bootstrap-konfidensinterval lavet vha. KI_typen.
  data <- stikfunc(pop, n)
  bootstrap_stik <-replicate(B, {stik <- sample(data, size = n, replace = TRUE)}) # Bootstrap-stikprøverne oprettes.
  bootstrap_fordeling <- c()
  bootstrap_se <- c()
  bootstrap_t <- c()
  
  for(i in 1:ncol(bootstrap_stik)){
    bootstrap_fordeling <- append(bootstrap_fordeling, mean(bootstrap_stik[,i])) # Middelværdien for hver bootstrap-stikprøve udregnes.
    bootstrap_se <- append(bootstrap_se, sd(bootstrap_stik[,i])) # Standardfejlen for hver bootstrap-stikprøve udregnes.
    bootstrap_t <- append(bootstrap_t, (mean(bootstrap_stik[,i])-mean(data))/bootstrap_se[i]) # T-værdien for hver bootstrap-stikprøve udregnes.
  }
  
  SortedData <- sort(bootstrap_fordeling)
  Sorted_t <- sort(bootstrap_t)
 # I de følgnede 3 if-statements, udregnes nedre og øvre grænser for konfidensintervaller vha. hhv. percentil, basic og t-metoden. 
  if(toString(KI_type)=="KI_Percentil" | toString(KI_type)=="P"){
    KI_nedre <- quantile(SortedData, probs = alpha/2, names = FALSE)
    KI_oevre <- quantile(SortedData, probs = 1-alpha/2, names = FALSE)
    percentil_KI <- c(KI_nedre, KI_oevre)
    return(percentil_KI)
  }
  else if(toString(KI_type)=="KI_Basic" | toString(KI_type)=="B"){
    theta_hat <- mean(data)
    KI_nedre <- 2*theta_hat-quantile(SortedData, probs = 1-alpha/2, names = FALSE)
    KI_oevre <- 2*theta_hat-quantile(SortedData, probs = alpha/2, names = FALSE)
    basic_KI <- c(KI_nedre, KI_oevre)
    return(basic_KI)
  }
  else if(toString(KI_type)=="KI_T" | toString(KI_type)=="T"){
    theta_hat <- mean(data)
    KI_nedre <- theta_hat-(quantile(Sorted_t, probs = 1-alpha/2, names = FALSE) * (sd(data))) 
    KI_oevre <- theta_hat-(quantile(Sorted_t, probs = alpha/2, names = FALSE) * (sd(data))) 
    KI_t <- c(KI_nedre, KI_oevre)
    return(KI_t)
  }
}
```




```{r}
daekningsgrad <- function(pop, n, r, KI){
  # Input
  ##  pop:    Populationen, der skal tages en stikprøve fra.
  ##  n:      Størrelse af stikprøven.
  ##  r:      Antal undersøgelser af, om stikprøvemiddelværdi er indeholdt i konfidensintervallet.
  ##  KI:     Konfidensintervallet.
  #
  # Output:   Dækningsgraden for konfidensintervallet KI.
  result <- replicate(r, {
    data <- sample(pop, n)
    middel <- mean(data)
    sandhed <- 0
    if(KI[1] <= middel & KI[2] >= middel){
      sandhed <- sandhed + 1
    }
    return(sandhed)
  })
  return(sum(result) / r * 100)
}
```

```{r}
vektor_daek <- function(pop, B, alpha, r, KI_type){
  # Input
  ##  pop:     Populationen, der skal tages en stikprøve fra.
  ##  B:       Antal bootstrap-stikprøver.
  ##  alpha:   Konfidensniveau.
  ##  r:       Antal undersøgelser af, om stikprøvemiddelværdi er indeholdt i konfidensintervallet.
  ##  KI_type: Type af konfidensinterval.
  #
  # Output:    Dækningsgraden for konfidenintervallet for forskellig stikprøvestørrelse.
  vektor <- c()
  for(n in seq(10,200,10)){
    KI <- konf(pop, n, B, alpha, KI_type) # Der oprettes et konfidensinterval vha. konf-funktionen. 
    daek <- daekningsgrad(pop, n, r, KI) # Dækningsgraden undersøge vha. daekningsgrads-funktionen. 
    vektor <- append(vektor, daek)
  }
  return(vektor)
}
```

```{r}
mean_daek <- function(rep, pop, B, alpha, r, KI_type){
  # Input
  ##  rep:     Antal gentagelser af vektordaek-funktionen.
  ##  pop:     Populationen, der skal tages en stikprøve fra.
  ##  B:       Antal bootstrap-stikprøver.
  ##  alpha:   Konfidensniveau.
  ##  r:       Antal undersøgelser af, om stikprøvemiddelværdi er indeholdt i konfidensintervallet.
  ##  KI_type: Type af konfidensinterval.
  #
  # Output:    Middelværdien af rep-antal konfidensintervaller.
  reps <- replicate(rep, {
    matrix_daek <- vektor_daek(pop, B, alpha, r, KI_type)
  }) # Gentager vektor_daek-funktionen rep antal gange, hvilket giver en matrix hvor hver søjle indholder dækningsgraden for rep antal konfidensintevaller ved stikprøvestørrelse 10, 20, ..., 200. 
  vek <- c()
  for(i in 1:ncol(reps)){
    vek <- append(vek, mean(reps[,i]))
  } # Beregner middelværdien af hver søjle i matricen reps. 
  return(vek)
}
```


```{r}
pop <- rbeta(n = 10000, shape1 = 8, shape2 = 2)
MeanDaek(rep = 10, pop, B = 1000, alpha = 0.05, r = 1000, KI_type = "P") 
MeanDaek(rep = 10, pop, B = 1000, alpha = 0.05, r = 1000, KI_type = "B")
MeanDaek(rep = 10, pop, B = 1000, alpha = 0.05, r = 1000, KI_type = "T")
```

```{r}
mat <- matrix(ncol = 3, nrow = 0)
mat <- rbind(mat, c(1:3))
mat <- rbind(mat, c(4:6))
mat
```


