--- 
title: "P2 - Simulering af Data"
author: "Gruppe B2-19"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
# biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
#description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
```{r, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE)
```

# Introduktion

## Forord

Projektet er udarbejdet af gruppe B2-19 fra Datavidenskab 2. semester på Aalborg Universitet. Projketperioden løb fra den 3. februar 2020 til den 27. maj 2020. Gruppen blev vejledt af Mikkel Meyer Andersen. Det overordnede tema i projektet er "Fra Data til Videnskab" med fokus på statistisk inferens ved hjælp af simuleringer. Projektets kildekode kan findes på følgende [link til GitHub](https://github.com/MadsCorfixen/Datavidenskab-P2/tree/master/Bookdown/bookdown-demo-master).

<!-- ## Synopsis -->

<!-- Projektet har haft til formål at afdække, hvilke alternativer der er til klassiske inferensmetoder, hvis disses antagelser ikke er overholdt.  -->

<!-- Først beskrives en klassisk inferensmetode, t-testen, og hvordan denne kan bruges til hypotesetests. Dernæst undersøges, hvordan tilsyneladende tilfældige tal kan genereres ved hjælp af algoritmer og hvordan programmeringssproget R kan udnyttes, til at udføre disse simuleringer hurtigt og simpelt. Herefter undersøges det, ved hjælp af simuleringer, om resultaterne er troværdige, hvis stikprøverne ikke er normalfordelte, når der arbejdes med en uparret t-test. Bagefter redegøres der for to alternativer til t-testen der ikke antager normalfordelte stikprøver, permutationer og bootstrap.  -->

<!-- Der blev fundet frem til at det ikke kan antages, at en t-test på en ikke-normalfordelt stikprøve altid giver retvisende resultater. Desuden blev det fundet frem til, at permutationstesten er mere præcis end bootstrap, hvis der udelukkende skal foretages en hypotesetest. Derudover blev det konkluderet, at, ud af de tre undersøgte bootstrap-metoder til konfidensintervaller, er dækningsgraden af T-metoden den mest præcis. -->

<!-- ## Abstract -->

<!-- The aim of the project was to identify alternatives to classical inference methods if the assumptions of these were not met. -->

<!-- First, a classical inference method, the t-test, and how it can be used for hypothesis testing, is described. Next, it is examined how seemingly random numbers can be generated by algorithms, and how the programming language R can be utilized to perform these simulations quickly and simply. Then, by means of simulations, it is examined whether the results are credible if the samples are not normally distributed when working with an unpaired t-test. Afterwards, two alternatives to the t-test that do not assume normally distributed samples, permutations and bootstrap, are presented. -->

<!-- It was discovered that it cannot be assumed that a t-test on a non-normal random sample always produces true results. In addition, it was found that the permutation test is more accurate than bootstrap if only a hypothesis test is to be performed. Furthermore, it was concluded that, out of the three bootstrap methods examined for confidence intervals, the coverage of the T method is the most accurate. -->

## Læsevejledning

I denne rapport anvendes grunlæggende teori omkring klassisk statistisk inferens, derdover er der inddraget to metoder, permutation og bootstrap, for at kunne sammenligne og teste op mod de klassiske statistiske inferens metoder. 

I rapporten gøres der brug af programmeringssproget R, til at gennemfører simuleringer og analyse. Til simulerings og analyse delen i rapporten er der hovedsaglig anvende funktionaliteter fra R og pakken _Mosaic_. Derudover er der til nogle specifikke formål anvendt pakker, som er konstrueret til disse formål, disse pakker er _wPerm_ og _boot_. Rapportens enkelte dele er skrevet i Markdown, som efterfølgende er samlet til den færdige rapport ved hjælp af pakken _bookdown_.

Metoden bootstrap beskrives i et kapitel. Det er muligt at anvendes den som enten parametrsik-bootstrap eller ikke-parametrisk-bootstrap, dog har denne rapport fokus på den ikke-parametriske-bootstrap, fordi...? __FIXME__ 

Der anvendes samme _seed_$31,415$ i gennem alle kapitler, for at sikre, at der er kontinuitet i de resultater, som rapporten drager sine konklusioner på baggrund af.   

I rapporten gøres der brug af den engelske version af decimal- og tusindtalsseperator. Baggrund for dette er, denne metode anvendes i programmeringssproget R, og for derved at lette vekslingen mellem brødtekst og kode, fortsættes metoden ligeledes i selve rapporten. 

Det beskrives i rapporten, at udførelsen af bootstrap og permutation, kræver $10,000$ resamples for at give et nøjagtigt resultat. Der vil igennem rapporten være steder hvor disse resamples, af hensyn til den tilgængelige computerkraft, er reducere til henholdsvis 500 og 1000 resamples.   

Alle kilder er skrevet efter Harvard-metoden og angives i firkantede parenteser, [forfatternavn, årstal]. Refereres der til en bestemt side i kilden eller et tidspunkt i en video, vil dette fremgå lige efter årstallet.

<!-- - ```pakke::funktion```. -->
<!-- - Ikke-parametrisk bootstrap. -->
<!-- - Samme seed, ```31415```, i alle rapportens afsnit. -->
<!-- - Engelsk version af decimal- og tusindtalsseperator -->
<!-- - Antal bootstraps / permutationer // reps kontra computerkraft -->

## Anvendte pakker

I dette projekt er følgende pakker blevet anvendt.

1) ```bookdown```, [@R-bookdown]. Denne pakke muliggør at skrive hele rapporter i R ved hjælp af Markdown, og er derfor brugt til udarbejdelsen af hele rapporten.

2) ```mosaic```, [@R-mosaic]. Denne pakke indeholder flere funktionaliteter, der benyttes i statistike analyser. Pakken anvendes i samtlige afsnit i rapporten.

3) ```wPerm```, [@R-wPerm]. Denne pakke indeholder en funktion, der kan udføre hypotesetest ved hjælp af permutationstest. Pakken anvendes i afsnit \@ref(perm-pvaerdi).

4) ```boot```, [@R-boot]. Denne pakke indeholder funktioner, der benyttes til at oprette bootstrap-stikprøver og til at udarbejde bootstrap-konfidensintervaller. Pakken anvendes i afsnit \@ref(boot-standardfejl) og \@ref(boot-daekningsgrader).
