# Fremgangsmåden fra YouTube (DTU)
```{r}
set.seed(31415)
tf_vektor <- c()
for(n in seq(4, 100, 4)){
  pop_middel <- 10
  pop_sd <- 2
  stik <- rnorm(n, pop_middel, pop_sd)
  stik_middel <- mean(stik)
  stik_sd <- sd(stik)
  
  n_boot <- 1000
  byggemand_bob <- replicate(100, {
    boot_stik <- replicate(n_boot, rnorm(n, stik_middel, stik_sd))
    boot_means <- apply(boot_stik, 2, mean)
    ci <- quantile(boot_means, c(0.025, 0.975))
    tf <- ci[1] <= pop_middel & ci[2] >= pop_middel
  })
  tf_vektor <- append(tf_vektor, sum(byggemand_bob))
}
```

```{r}
x <- seq(4, 100, 4)
plot(x, tf_vektor/100, type="l", col="blue", ylab = "Dækningsgrad",
     xlab = "Stikprøvestørrelse")
abline(h=0.95, lty=5, col="black")

mean(tf_vektor)
```

# Hypotesetest (Uparret)

```{r}
set.seed(31415)
bootstraps <- 1000
n <- 20
m <- 50
pop_shape1 <- 2
pop_shape2 <- 8

res <- replicate(n = 100, {
  stik1 <- rbeta(n, shape1 = pop_shape1, shape2 = pop_shape2)
  stik2 <- rbeta(m, shape1 = pop_shape1, shape2 = pop_shape2)
  t_obs <- ((mean(stik1) - mean(stik2)) - (0)) /
              ((sd(stik1))^2 / n + ((sd(stik2))^2 / m))
  
  # Beregner bedste bud på parametre for stikprøve 1
  stik1_middel <- mean(stik1)
  stik1_sd <- sd(stik1)
  stik1_shape1 <- ((((1 - stik1_middel)/(stik1_sd)^2) - (1/stik1_middel)))*stik1_middel^2
  stik1_shape2 <- stik1_shape1*((1/stik1_middel) - 1)
  
  # Beregner bedste bud på parametre for stikprøve 2
  stik2_middel <- mean(stik2)
  stik2_sd <- sd(stik2)
  stik2_shape1 <- ((((1 - stik2_middel)/(stik2_sd)^2) - (1/stik2_middel)))*stik2_middel^2
  stik2_shape2 <- stik2_shape1*((1/stik2_middel) - 1)
  
  boot_t <- replicate(n = bootstraps, {
    boot_x <- rbeta(n, shape1 = stik1_shape1, shape2 = stik1_shape2)
    boot_y <- rbeta(m, shape1 = stik2_shape1, shape2 = stik2_shape2)

    boot_test <- ((mean(boot_x) - mean(boot_y)) -
                    (mean(stik1) - mean(stik2))) /
                      (((sd(boot_x))^2 / n) +
                        ((sd(boot_y))^2 / m))
  })
  
  antal_ekstreme <- abs(boot_t) >= abs(t_obs)

  p_vaerdi <- (sum(antal_ekstreme)+1) / (bootstraps + 1)
})

p_vaerdi_uparret <- mean(res)
p_vaerdi_uparret
```

```{r}
set.seed(31415)
bootstraps <- 1000
n <- 20
m <- 50
pop_shape1 <- 2
pop_shape2 <- 8
konf_niveau <- 0.95
reps <- 1000

type_1_fejl <- replicate(n = reps, {
  stik1 <- rbeta(n, shape1 = pop_shape1, shape2 = pop_shape2)
  stik2 <- rbeta(m, shape1 = pop_shape1, shape2 = pop_shape2)
  t_obs <- ((mean(stik1) - mean(stik2)) - (0)) / ((sd(stik1))^2 / n + ((sd(stik2))^2 / m))
  
  stik1_middel <- mean(stik1)
  stik1_sd <- sd(stik1)
  stik1_shape1 <- ((((1 - stik1_middel)/(stik1_sd)^2) - (1/stik1_middel)))*stik1_middel^2
  stik1_shape2 <- stik1_shape1*((1/stik1_middel) - 1)
  
  stik2_middel <- mean(stik2)
  stik2_sd <- sd(stik2)
  stik2_shape1 <- ((((1 - stik2_middel)/(stik2_sd)^2) - (1/stik2_middel)))*stik2_middel^2
  stik2_shape2 <- stik2_shape1*((1/stik2_middel) - 1)
  
  boot_t <- replicate(n = bootstraps, {
    boot_x <- rbeta(n, shape1 = stik1_shape1, shape2 = stik1_shape2)
    boot_y <- rbeta(m, shape1 = stik2_shape1, shape2 = stik2_shape2)

    boot_test <- ((mean(boot_x) - mean(boot_y)) -
                    (mean(stik1) - mean(stik2))) /
                      (((sd(boot_x))^2 / n) +
                        ((sd(boot_y))^2 / m))
  })

  antal_ekstreme <- abs(boot_t) >= abs(t_obs)

  p_vaerdi <- (sum(antal_ekstreme)+1) / (bootstraps + 1)
  type1fejl <- p_vaerdi > 1 - konf_niveau
  return(type1fejl)
})

fejltable <- table(type_1_fejl)
fejltable
```



