
```{r}
#set.seed(2)
pop_middel = 10

vector_p <- c()
vector_b <- c()
vector_t <- c()

for(n in seq(4, 100, 4)){
  
  stik <- rnorm(n, pop_middel, 1)
  middel_stik <- mean(stik)
  sd_stik <- sd(stik)
  
  r = 100
  res <- replicate(r, {
    simSamples <- replicate(r, rnorm(n, middel_stik, sd_stik))

    simMeans <- apply(simSamples, 2, mean)
  
    konf_p <- quantile(simMeans, c(0.025, 0.975))
    konf_b <- 2 * middel_stik - quantile(simMeans, c(0.975, 0.025))
    konf_t <- middel_stik - ((quantile(simMeans, c(0.975, 0.025)) - middel_stik)/sd(simSamples)) *    
    sd_stik
    
    tf_p <- konf_p[1] <= pop_middel & konf_p[2] >= pop_middel
    tf_b <- konf_b[1] <= pop_middel & konf_b[2] >= pop_middel
    tf_t <- konf_t[1] <= pop_middel & konf_t[2] >= pop_middel
    
    return(c(tf_p, tf_b, tf_t))
  })
  
  # print(res)
  # print(sum(res[1,]))
  # print(sum(res[1,])/r)
  
  vector_p <- append(vector_p, mean(res[1,]))
  vector_b <- append(vector_b, mean(res[2,]))
  vector_t <- append(vector_t, mean(res[3,]))
}

#print(vector_p)
```


```{r}
x <- seq(4, 100, 4)
plot(x, vector_p, type="l", col="red", ylab = "Dækningsgrad",
      xlab = "Stikprøvestørrelse", ylim = c(0, 1))
lines(x, vector_b, type="l", col="blue")
lines(x, vector_t, type="l", col="green")
abline(h=0.95, lty=5, col="black")
```


```{r}
set.seed(2)
n <- 20
m <- 50
konf_niveau <- 0.95
sand_middel <- 0

type_1_fejl_boot <- replicate(n = 500, {
  stik1 <- rbeta(n, shape1 = 2, shape2 = 8)
  stik2 <- rbeta(m, shape1 = 2, shape2 = 8)
  
  #stik_diff <- stik1 - stik2
  t_obs <- ((mean(stik1) - mean(stik2)) - (0)) /
            sqrt(((sd(stik1))^2 / n) +
              ((sd(stik2))^2 / m))

  boot_t <- c()
  for(i in seq(1, bootstraps)){
    boot <- sample(x = c(stik1, stik2), replace = TRUE)
    
    boot_x <- boot[1 : n] # Bootstrap-stikprøve 1
    boot_y <- boot[(n + 1) : (n + m)] # Bootstrap-stikprøve 2
    
    boot_t[i] <- ((mean(boot_x) - mean(boot_y)) -
                    (mean(stik1) - mean(stik2))) /
                      sqrt(((sd(boot_x))^2 / n) +
                        ((sd(boot_y))^2 / m))
  }

  antal_ekstreme <- abs(boot_t) >= abs(t_obs)

  p_vaerdi <- (sum(antal_ekstreme)+1) / (bootstraps + 1)
  
  andel <- p_vaerdi > 1 - konf_niveau
})

type_1_uparret <- table(type_1_fejl_boot)
type_1_uparret
```

