# Parametre

```{r}
library(gtools) # Benyttes til permutationstest
set.seed(31415)
n <- 5
alfa <- 8
beta <- 2
konf_niveau <- 0.95
sand_middel <- 0
reps <- 100
B <- 1000 # Antal bootstrap-resamples
```

# T-test uparret

```{r}
type_1_fejl_t <- replicate(reps, {
  Stik1 <- rbeta(n, 80, 20)
  Stik2 <- rbeta(n, 8, 2)
  test <- t.test(Stik1, Stik2, alternative = "two.sided", mu = sand_middel, conf.level = konf_niveau, var.equal = FALSE)
  andel <- test$p.value > 1-konf_niveau
})

table(type_1_fejl_t)
```

# Permutationstest uparret (Kilde MSRR s. 54)

```{r}
type_1_fejl_perm <- replicate(reps, {
  
  stik1 <- rbeta(n, alfa, beta)
  stik2 <- rbeta(n, alfa, beta)
  samlet_stik <- c(stik1, stik2) 
  
  mean_difference <- abs(mean(stik1) - mean(stik2))
  mean_list <- c()
  
  for(i in 1:(n*2)){
    permuteret_samlet_stik <- gtools::permute(samlet_stik)
    permuteret_stik1 <- head(permuteret_samlet_stik, n)
    permuteret_stik2 <- tail(permuteret_samlet_stik, n)
  
    mean_list[i] <- abs(mean(permuteret_stik1) - mean(permuteret_stik2))
  }
  
  stoerre_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     stoerre_vaerdier <- stoerre_vaerdier + 1
   }
  }
  
  mindre_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     mindre_vaerdier <- mindre_vaerdier + 1
   }
  }

  p_value <- p_value <- 2*(min(mindre_vaerdier, stoerre_vaerdier))/length(mean_list)
  
  type1fejl <- p_value > 1 - konf_niveau
  return(type1fejl)
})

table(type_1_fejl_perm)
```

# Bootstrap uparret

```{r}
type_1_fejl_boot <- replicate(reps, {
  stik1 <- rbeta(n, alfa, beta)
  stik2 <- rbeta(n, alfa, beta)
  samlet_stik <- c(stik1, stik2)
  
  mean_difference <- abs(mean(stik1) - mean(stik2))
  
  mean_list <- c()
  
  for(i in 1:B){
    boot1 <- sample(samlet_stik, n, replace = TRUE)
    boot2 <- sample(samlet_stik, n, replace = TRUE)
    
    mean_list[i] <- abs(mean(boot1) - mean(boot2))
  }
  
  stoerre_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     stoerre_vaerdier <- stoerre_vaerdier + 1
   }
  }
  
  mindre_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     mindre_vaerdier <- mindre_vaerdier + 1
   }
  }
  
  p_value <- 2*(min(mindre_vaerdier, stoerre_vaerdier))/B
  
  type1fejl <- p_value > 1 - konf_niveau
  return(type1fejl)
})

table(type_1_fejl_boot)
```



























