```{r}
library(boot)
```

input: stikprøvestørrelse og parameter
```{r}
meanFunc <- function(sample_pop,i){
  mean(sample_pop[i])
}
```

```{r}
library(boot)
sand_middel <- 8/(8+2)
```

```{r}
matriks_p <- matrix(ncol = 25, nrow = 100)
vector_p <- c()
for(n in seq(4, 100, 4)){
  res <- replicate(100,{
    stik <- rbeta(n, 8, 2)
    boot_stik <- boot(stik, statistic = meanFunc, 10000)
    interval_perc <- suppressWarnings(boot.ci(boot_stik, type = c("perc"))$percent[4:5])
    tf <- interval_perc[1]<=sand_middel & interval_perc[2]>=sand_middel
  })
  matriks_p[,n/4] <- res
  vector_p <- append(vector_p, mean(matriks_p[,n/4]))
}
```

```{r}
matriks_b <- matrix(ncol = 25, nrow = 100)
vector_b <- c()
for(n in seq(4, 100, 4)){
  res <- replicate(100,{
    stik <- rbeta(n, 8, 2)
    boot_stik <- boot(stik, statistic = meanFunc, 10000)
    interval_basic <- suppressWarnings(boot.ci(boot_stik, type = c("basic"))$basic[4:5])
    tf <- interval_basic[1]<=sand_middel & interval_basic[2]>=sand_middel
  })
  matriks_b[,n/4] <- res
  vector_b <- append(vector_b, mean(matriks_b[,n/4]))
}
```

```{r}
matriks_n <- matrix(ncol = 25, nrow = 100)
vector_n <- c()
for(n in seq(4, 100, 4)){
  res <- replicate(100,{
    stik <- rbeta(n, 8, 2)
    boot_stik <- boot(stik, statistic = meanFunc, 10000)
    interval_normal <- suppressWarnings(boot.ci(boot_stik, type = c("norm"))$normal[2:3])
    tf <- interval_normal[1]<=sand_middel & interval_normal[2]>=sand_middel
  })
  matriks_n[,n/4] <- res
  vector_n <- append(vector_n, mean(matriks_n[,n/4]))
}
```

```{r}
x <- seq(4, 100, 4)
plot(x, vector_p, type="l", col="red", ylab = "Dækningsgrad", xlab = "Stikprøvestørrelse")
lines(x, vector_b, type="l", col="blue")
lines(x, vector_n, type="l", col="green")
abline(h=0.95, lty=5, col="black")
legend(85, 0.8, legend=c("Percentil", "Basic", "Normal"),
       col=c("red", "blue", "green"), lty=c(1,1,1), cex=0.8)
```

```{r}
x <- rnorm(10000)
x0 <- 2
y <- density(dnorm(x, log = FALSE))
y0 <- y$y[findInterval(x0, y$x)]

plot(function(x) dnorm(x, log = FALSE), -3, 3,
     xlab = "", ylab = "", xaxt = "n", yaxt = "n")
abline(v=2, lty=5, col="red")
abline(v=-2, lty=5, col="red")
#segments(x0, 0, x0, y0)
```

```{r}
library(mosaic)
xcbinom(0.96, size = 5000, prob = 0.50, return="plot", ylab = "")
```


