# Stikprøver

```{r}
library(gtools) # Benyttes til permutationstest

n <- 20
alpha <- 8
beta <- 2
```

# T-test

```{r}
type_1_fejl_t <- replicate(100, {
  Stik1 <- rbeta(n, alpha, beta)
  Stik2 <- rbeta(n, alpha, beta)
  test <- t.test(Stik1, Stik2, alternative = "two.sided", mu = 0, conf.level = 0.95)
  andel <- test$p.value > 0.05
})

table(type_1_fejl_t)
```

# Permutationstest (Kilde MSRR s. 54)

```{r}
type_1_fejl_perm <- replicate(100, {
  
  stik1 <- rbeta(n, alpha, beta)
  stik2 <- rbeta(n, alpha, beta)
  samlet_stik <- c(stik1, stik2) 
  
  mean_difference <- abs(mean(stik1) - mean(stik2))
  mean_list <- c()
  
  for(i in 1:(n*2)){
    permuteret_samlet_stik <- gtools::permute(samlet_stik) # Den samlede stikprøve permuteres
    permuteret_stik1 <- head(permuteret_samlet_stik, n) # Den første halvdel af den samlede, permuterede stikprøve
    permuteret_stik2 <- tail(permuteret_samlet_stik, n) # Den sidste halvdel af den samlede, permuterede stikprøve
  
    mean_list[i] <- abs(mean(permuteret_stik1) - mean(permuteret_stik2))
  }
  
  ekstreme_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     ekstreme_vaerdier <- ekstreme_vaerdier + 1
   }
  }
  p_value <- ekstreme_vaerdier/length(mean_list)
  
  type1fejl <- p_value > 0.05
  return(type1fejl)
})

table(type_1_fejl_perm)
```

# Bootstrap

```{r}
type_1_fejl_boot <- replicate(100, {
  stik1 <- rbeta(n, alpha, beta)
  stik2 <- rbeta(n, alpha, beta)
  samlet_stik <- c(stik1, stik2)
  
  mean_difference <- abs(mean(stik1) - mean(stik2))
  
  mean_list <- c()
  
  for(i in 1:1000){
    boot1 <- sample(samlet_stik, n, replace = TRUE)
    boot2 <- sample(samlet_stik, n, replace = TRUE)
    
    mean_list[i] <- abs(mean(boot1) - mean(boot2))
  }
  
  ekstreme_vaerdier <- 0
  for(i in 1:length(mean_list)){
    if(mean_list[i] >= mean_difference){
     ekstreme_vaerdier <- ekstreme_vaerdier + 1
   }
  }
  p_value <- ekstreme_vaerdier/length(mean_list)
  
  type1fejl <- p_value > 0.05
  return(type1fejl)
})

table(type_1_fejl_boot)
```


























